easy_admin:
    site_name: 'Symfony<i>Biblio</i> Administration'
    entities:
      # List the entity class name you want to manage
      #  - App\Entity\Product
      #  - App\Entity\Category
      # - App\Entity\User
        User:
            # label: menu.users
            class: App\Entity\User
            list:
                fields: ['id', 'email', 'prenom', 'nom', 'adresse', 'telephone', 'roles']
    design:
        brand_color: '#1ABC9C'
        assets:
            css: 
                - 'css/custom-backend.css'
        menu:
            # - { label: 'Public Homepage', route: index' }
